### ISSUE TITLE
1.6.4 is polluting arrays with a 'sequence' property

### ISSUE THREAD

**Issue by meganwalker-ibm** [jsonata-js/jsonata#296]
PR https://github.com/jsonata-js/jsonata/pull/292 included in JSONata 1.6.4 started polluting data returned to consumers with a 'sequence' property attached onto an array.

I don't think this internal property should be externalised to consumers; especially in a way that means it can't be serialised losslessly into a string.

![screenshot 2019-01-14 at 10 59 58](https://user-images.githubusercontent.com/20321922/51109710-ed73fb80-17ed-11e9-8a5f-ffc1c1514879.png)

The `sequence` property here is added by JSONata, not from the data we are working with, and it cannot be serialised correctly into JSON (Nor can the equivalent JSON string be parsed into javascript)
```
{
  "foo": {
    "bar": [
      {
        "name": "freddy",
        "price": 6
      },
      {
        "name": "jsonata",
        "price": 1000000
      },
      sequence: true
    ]
  }
}
```
Represents the returned data structure, except it's not valid JSON.

**Comment by andrew-coleman** [comment]
How are you serializing to JSON?  The following Javascript code:
```
const arr = [1,2,3];
arr.sequence=true;
JSON.stringify(arr);
```
produces 
`"[1,2,3]"`

**Comment by andrew-coleman** [comment]
The `sequence` property was always there, but it used to be created using `Object.defineProperty` with `enumerable` set to false.  However, this had a significant performance hit, and rewriting it this way gave a 3x performance improvement on the expression `$sum(Account.Order.Product.(Price*Quantity))`.  If you can come up with an alternative solution that doesn't degrade performance, I'd welcome it.

**Comment by mattbaileyuk** [comment]
I was aware that the `sequence` property was there internally before as processing is taking place, and hence didn't feel concerned by the change in the PR, I didn't realise that this would have an impact on what was returned from an `evaluate()` call, which is an external change. Having `evaluate()` return a `sequence` property is new behaviour in 1.6.4.

**Comment by mtiller** [comment]
FYI, in my (TypeScript) implementation, I always "wrapped" the values in a wrapper where the sequence and a few other properties were properties of the wrapper, not of the actual value.  This allowed me to include any such properties pretty easily.  I would unwrap such values before calling functions, for example.

Now, that approach may have had a significant impact on performance, I have no idea.  I didn't do any performance benchmarking.

**Comment by edbrannin** [comment]
Possibly related: I'm seeing `keepSingleton: true` instead of `sequence: true` in arrays of Strings.

**Comment by cherukurisurendra2010** [comment]
Hi Team,

We are facing the same issue, we are getting extra sequence key.

Could you please provide any updated status on this bug.

Thanks.

**Comment by andrew-coleman** [comment]
The 'status' is as discussed above.  Any changes in this area could have significant performance impact.  Before touching this, we need a framework for measuring performance so that we can be certain of no regressions.

These properties are only added to the Array object.  When you JSON.serialize() the structure, they don't appear in the output.

**Comment by loganvolkers** [comment]
The other option is to have a final "sanitization" step that makes sure that a clean array is returned.
```
function cleanOutput(raw) {
  if (Array.isArray(raw)) {
    return [...raw];
  } else {
    return raw;
  }
}
```
This could be done as a final step in `evaluate`, but it can also be done externally.
```
const jsonata = require("jsonata");
let input = {
  units: [
    {
      name: "bob",
      price: 20
    },
    {
      name: "jessica",
      price: 500
    },
    {
      name: "may",
      price: 40
    }
  ]
};
const output = jsonata("units[price > 20]").evaluate(input);
output.keepSingleton = "bar" // For illustration only
console.log(output, Object.keys(output));
const clean = cleanOutput(output);
console.log(clean, Object.keys(clean));
```
The above code outputs
```
["0", "1", "sequence", "keepSingleton"]
["0", "1"]
```

This could provide an immediate workaround for:
 - @edbrannin concern about `keepSingleton`
 - @cherukurisurendra2010 concern about `sequence`

I'll leave the performance fix and potential for integration into core up to @andrew-coleman. If performance is a big concern, maybe we can get a jsonata->webassembly compiler written ;)

**Comment by ameinhardt** [comment]
@loganvolkers : that doens't work for nested arrays, does it?
How about:
```javascript
cleanOutput = JSON.parse(JSON.stringify(raw))
```

**Comment by knolleary** [comment]
I have been looking at this issue in related to #473.

I've got a simple performance test that runs the `$sum(Account.Order.Product.(Price*Quantity))` expression 100000 times, across 10 separate runs, and then averages the time taken and number of evals/sec.

I have used that to compare some possible approaches to resolving this issue:

1. `Object.defineProperty` to make the properties non-enumerable. As @andrew-coleman said, this is known to be slower, but I tried it out to get a sense of how much slower given the current code.
2. `WeakMap` - this uses a WeakMap in `util.js` to track the 'known' sequence arrays, rather than having to flag the array itself
3. Subclass Array - create a custom class that extends Array, so we can use `instanceof` to check its type, but still looks just like an Array.
         
       class Sequence extends Array {}


| Code | evals/sec  |
|---------|---------:|
|existing| 40891     |
|`Object.defineProperty` | 29178 |
|`WeakMap` | 23581 |
|subclass Array| 30491 |

So yeah... no quick win with those options.

Also, having got this far, I realise there's more to it than just being able to identify it as a sequence - there is also the `keepSingleton` property used in some places that gets added to the object. So I'm going to post this comment as a record of my failure to find a performant fix so far.

**Comment by andrew-coleman** [comment]
Thanks Nick! :)

**Comment by agarwalamit662** [comment]
Any update on this issue ..? I am getting sequence property in my arrays.

**Comment by pankleks** [comment]
I have a problem when I create in jsonata field called "sequence", when I test it on jsonata playground it's working fine.

But when I do it in my App (JS) the field is not created.

If I rename field to something else like "seq" all is fine.

Can it be somehow realted?

**Comment by kolban-google** [comment]
+1 on this issue!!!

**Comment by sban2009** [comment]
+1

**Comment by koladilip** [comment]
We are also facing this issue, can this be fixed?

**Comment by Woodz** [comment]
Please consider adding a sanitisation step before returning the data from JSONATA library, because JS test libraries fail without a clear reason due to this internal field. Currently we need to pass all the responses from JSONATA through `JSON.parse(JSON.stringify` to workaround this issue

**Comment by Woodz** [comment]
> The `sequence` property was always there, but it used to be created using `Object.defineProperty` with `enumerable` set to false. However, this had a significant performance hit, and rewriting it this way gave a 3x performance improvement on the expression `$sum(Account.Order.Product.(Price*Quantity))`. If you can come up with an alternative solution that doesn't degrade performance, I'd welcome it.

@andrew-coleman please reconsider prioritising performance ahead of functionality/ease of usage. I sincerely doubt that the majority of your users will have issues with the library being 4x slower, whereas these implementation details seem to be causing a lot of issues based on the number of issues and comments about them

**Comment by airandfingers** [comment]
+1, this issue has been causing our test assertions (specifically, Vitest/Jest's `.toBeCalledWith({ key: expect.any(String) })` to fail with baffling error messages like `Compared values have no visual difference`, wasting hours of developer time.

We can use [lodash.cloneDeep](https://lodash.com/docs/4.17.15#cloneDeep) everywhere as a workaround, but _we shouldn't have to_ - jsonata should be fixed to clean up these extraneous values, even at the cost of some microseconds for each call.

**Comment by chubshaun** [comment]
@andrew-coleman 

This seems like a pretty big issue. I would argue that performance at the cost of accuracy (JSONata polluting data structures) is not worth it.
 
We've been "kludging" by doing a `JSON.parse(JSON.stringify(result))` at the end to workaround it. Please consider:

- Adding a boolean option like `stripJSONataData` that will handle this automatically at the cost of some performance.

- Calling this issue out front and center in the docs/readme. The only reason we figured out what was going on was by looking through the Github Issues.

**Comment by jamietanna** [comment]
Thanks for the suggestions here, I came here via a Jest error `serializes to the same string` which indicated the `sequence: true` but wasn't till I arrived here did I realise why



<details>

<summary>Full error</summary>

```
JestAssertionError: expect(received).resolves.toEqual(expected) // deep equality

Expected: {"releases": [{"version": "1.20.1"}, {"version": "1.18.2"}]}
Received: serializes to the same string
    at Object.toEqual (/home/jamie/workspaces/_external/jvt.me/tmp/renovate-test-harness/node_modules/expect/build/index.js:174:22)
    at Object.<anonymous> (/home/jamie/workspaces/_external/jvt.me/tmp/renovate-test-harness/renovate.spec.ts:89:67)
    at Promise.then.completed (/home/jamie/workspaces/_external/jvt.me/tmp/renovate-test-harness/node_modules/jest-circus/build/utils.js:298:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/home/jamie/workspaces/_external/jvt.me/tmp/renovate-test-harness/node_modules/jest-circus/build/utils.js:231:10)
    at _callCircusTest (/home/jamie/workspaces/_external/jvt.me/tmp/renovate-test-harness/node_modules/jest-circus/build/run.js:316:40)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at _runTest (/home/jamie/workspaces/_external/jvt.me/tmp/renovate-test-harness/node_modules/jest-circus/build/run.js:252:3)
    at _runTestsForDescribeBlock (/home/jamie/workspaces/_external/jvt.me/tmp/renovate-test-harness/node_modules/jest-circus/build/run.js:126:9)
    at _runTestsForDescribeBlock (/home/jamie/workspaces/_external/jvt.me/tmp/renovate-test-harness/node_modules/jest-circus/build/run.js:121:9)
    at _runTestsForDescribeBlock (/home/jamie/workspaces/_external/jvt.me/tmp/renovate-test-harness/node_modules/jest-circus/build/run.js:121:9)
    at _runTestsForDescribeBlock (/home/jamie/workspaces/_external/jvt.me/tmp/renovate-test-harness/node_modules/jest-circus/build/run.js:121:9)
    at run (/home/jamie/workspaces/_external/jvt.me/tmp/renovate-test-harness/node_modules/jest-circus/build/run.js:71:3)
    at runAndTransformResultsToJestFormat (/home/jamie/workspaces/_external/jvt.me/tmp/renovate-test-harness/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/home/jamie/workspaces/_external/jvt.me/tmp/renovate-test-harness/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/home/jamie/workspaces/_external/jvt.me/tmp/renovate-test-harness/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/home/jamie/workspaces/_external/jvt.me/tmp/renovate-test-harness/node_modules/jest-runner/build/runTest.js:444:34) {
  matcherResult: {
    actual: {
      releases: [
        { version: '1.20.1' },
        { version: '1.18.2' },
        sequence: true,
        keepSingleton: true
      ]
    },
    expected: { releases: [ { version: '1.20.1' }, { version: '1.18.2' } ] },
    message: '\x1B[2mexpect(\x1B[22m\x1B[31mreceived\x1B[39m\x1B[2m).\x1B[22mresolves\x1B[2m.\x1B[22mtoEqual\x1B[2m(\x1B[22m\x1B[32mexpected\x1B[39m\x1B[2m) // deep equality\x1B[22m\n' +
      '\n' +
      'Expected: \x1B[32m{"releases": [{"version": "1.20.1"}, {"version": "1.18.2"}]}\x1B[39m\n' +
      'Received: serializes to the same string',
    name: 'toEqual',
    pass: false
  }
}
```

</details>

I've gotten around it with the `JSON.parse(JSON.stringify(result))` workaround
