### ISSUE TITLE
JSONata does not return a position for syntax error 'unexpected end of expression'

### ISSUE THREAD

**Issue by blgm** [jsonata-js/jsonata#37]
JSONata has an implicit contract to return a position index when there is an error.  Consider the following test which is an extension of [an existing test](https://github.com/jsonata-js/jsonata/blob/f455019f46669b922b972afc719dabcc401a105c/test/jsonata-test.js#L7430), updated to check the position:
```
    describe('Error cases - (Evaluate)', function () {
        describe('General', function () {
            it.only('Closing brackets are mandatory', function () {
                expect(function () {
                    jsonata('$lowercase("Missing close brackets"').evaluate(person);
                }).to.throw()
                    .to.deep.contain({token: '(end)', value: ')', position: 35})
                    .to.have.property('message').to.match(/Syntax error: expected \'\)\' before end of expression/);
            });
```

It fails with:
```
  1) #evaluate Error cases - (Evaluate) General Closing brackets are mandatory:
     AssertionError: expected { Object (message, stack, ...) } to have a property 'position' of 35, but got undefined
      at Assertion.include (node_modules/chai/lib/chai/core/assertions.js:221:47)
      at Assertion.assert (node_modules/chai/lib/chai/utils/addChainableMethod.js:84:49)
      at Context.<anonymous> (test/jsonata-test.js:7434:30)
```

JSONata should be updated so that it returns a position in this situation.  The position could either be the unmatched token (`10`) or the end of the expression (`35`).

**Comment by andrew-coleman** [comment]
Fixed in latest commit on branch 1.1
Many thanks.
