### ISSUE TITLE
ES5 generation fails, please help!

### ISSUE THREAD

**Issue by AstroNet-K2** [jsonata-js/jsonata#395]
Log as shown below.

PS C:\Jsonata-now> npm run build-es5

> jsonata@1.7.0 build-es5 C:\Jsonata-now
> npm run mkdir-dist && npm run regenerator && npm run browserify-es5 && npm run minify-es5

> jsonata@1.7.0 mkdir-dist C:\Jsonata-now
> mkdirp ./dist

> jsonata@1.7.0 regenerator C:\Jsonata-now
> babel src --out-dir dist --presets=@babel/env

Successfully compiled 6 files with Babel.

> jsonata@1.7.0 browserify-es5 C:\Jsonata-now
> regenerator --include-runtime polyfill.js > jsonata-es5.js; browserify dist/jsonata.js --standalone jsonata >> jsonata-es5.js

> jsonata@1.7.0 minify-es5 C:\Jsonata-now
> uglifyjs jsonata-es5.js -o jsonata-es5.min.js --compress --mangle

Parse error at jsonata-es5.js:1,37
Usage: regenerator [options] <source directory> <output directory> [<module ID>
                                     ^
ERROR: Unexpected token: name (directory)
    at JS_Parse_Error.get (eval at <anonymous> (C:\Jsonata-now\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:75:23)
    at fatal (C:\Jsonata-now\node_modules\uglify-es\bin\uglifyjs:300:53)
    at run (C:\Jsonata-now\node_modules\uglify-es\bin\uglifyjs:239:9)
    at Object.<anonymous> (C:\Jsonata-now\node_modules\uglify-es\bin\uglifyjs:169:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
npm ERR! code ELIFECYCLE
npm ERR! jsonata@1.7.0 minify-es5: `uglifyjs jsonata-es5.js -o jsonata-es5.min.js --compress --mangle`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsonata@1.7.0 minify-es5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USERHOME\AppData\Roaming\npm-cache\_logs\2019-12-12T10_33_03_091Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsonata@1.7.0 build-es5: `npm run mkdir-dist && npm run regenerator && npm run browserify-es5 && npm run minify-es5`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsonata@1.7.0 build-es5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USERHOME\AppData\Roaming\npm-cache\_logs\2019-12-12T10_33_03_143Z-debug.log
PS C:\Jsonata-now> npm -version
6.9.0

**Comment by AstroNet-K2** [comment]
My package.json here:

`{
  "name": "jsonata",
  "version": "1.7.0",
  "description": "JSON query and transformation language",
  "module": "jsonata.js",
  "main": "jsonata.js",
  "typings": "jsonata.d.ts",
  "homepage": "http://jsonata.org/",
  "repository": {
    "type": "git",
    "url": "https://github.com/jsonata-js/jsonata.git"
  },
  "scripts": {
    "pretest": "npm run lint",
    "mocha": "node ./node_modules/istanbul/lib/cli.js cover --report cobertura --report html ./node_modules/mocha/bin/_mocha -- \"test/**/*.js\"",
    "test": "npm run mocha",
    "posttest": "npm run check-coverage && npm run browserify && npm run minify && npm run build-es5",
    "build-es5": "npm run mkdir-dist && npm run regenerator && npm run browserify-es5 && npm run minify-es5",
    "check-coverage": "istanbul check-coverage -statement 100 -branch 100 -function 100 -line 100",
    "browserify": "browserify src/jsonata.js --outfile jsonata.js --standalone jsonata",
    "mkdir-dist": "mkdirp ./dist",
    "regenerator": "babel src --out-dir dist --presets=@babel/env",
    "browserify-es5": "regenerator --include-runtime polyfill.js > jsonata-es5.js; browserify dist/jsonata.js --standalone jsonata >> jsonata-es5.js",
    "prepublishOnly": "npm run browserify && npm run minify && npm run build-es5",
    "lint": "eslint src",
    "doc": "jsdoc --configure jsdoc.json .",
    "cover": "istanbul cover _mocha",
    "coveralls": "npm run cover -- --report lcovonly && cat ./coverage/lcov.info | coveralls",
    "minify": "uglifyjs jsonata.js -o jsonata.min.js --compress --mangle",
    "minify-es5": "uglifyjs jsonata-es5.js -o jsonata-es5.min.js --compress --mangle"
  },
  "license": "MIT",
  "keywords": [
    "JSON",
    "query",
    "transformation",
    "transform",
    "mapping",
    "path"
  ],
  "devDependencies": {
    "@babel/cli": "^7.6.2",
    "@babel/core": "^7.6.2",
    "@babel/preset-env": "^7.6.2",
    "babel-preset-env": "^1.7.0",
    "browserify": "^16.5.0",
    "chai": "^4.2.0",
    "chai-as-promised": "^7.1.1",
    "coveralls": "^3.0.6",
    "eslint": "^6.5.1",
    "eslint-plugin-ideal": "^0.1.3",
    "istanbul": "^0.4.5",
    "jsdoc": "^3.6.3",
    "mkdirp": "^0.5.1",
    "mocha": "^6.2.1",
    "mocha-lcov-reporter": "^1.3.0",
    "regenerator": "^0.14.2",
    "request": "^2.88.0",
    "uglify-es": "^3.3.9"
  },
  "engines": {
    "node": ">= 8"
  }
}
`

**Comment by AstroNet-K2** [comment]
We are noticing this on windows environment only. On UNIX we are not seeing this issue.
Do we have any fix available for windows or any settings would help to overcome this?
Please check this soon. Thanks in advance!

**Comment by andrew-coleman** [comment]
I don't have immediate access to a windows box, @mattbaileyuk are you able to look at this please?

**Comment by mattbaileyuk** [comment]
I don't have access to a Windows machine at work, but I'll try and give this a go on my home PC in the next few days.

@AstroNet-K2 What are you using for your Windows environment? Git bash, command prompt, Powershell, the new Windows Terminal? If the `regenerator` command is doing something strange then it feels environment-specific (and possibly something that `regenerator` would fix as we just call it) and might be worth trying one of the other options.

**Comment by AstroNet-K2** [comment]
@mattbaileyuk and @andrew-coleman , thanks for responding.
 
I tried all possible options (Github bash, command prompt, powershell, Cygwin and VSCode terminal) on Windows. Everywhere its ending up with same error. As @mattbaileyuk rightly guessed, the `_regenerator_` or _`browserify`_ surely causing the issue with path resolution, so basically this following command is failing in the script.
`regenerator --include-runtime polyfill.js > jsonata-es5.js; browserify dist/jsonata.js --standalone jsonata >> jsonata-es5.js`

Really appreciate your time again, please help us out here as our whole DEV network machines runs on Windows 10 Version 1909 (OS Build 18363.535), and we want this es5 generation to be part of our build scripts so we need this to be working on Windows environment as well.

Thanks again.

**Comment by AstroNet-K2** [comment]
@mattbaileyuk and @andrew-coleman 
Would you please label this as a bug and have it assigned so that the script can be fixed to support the windows environment?

**Comment by andrew-coleman** [comment]
@AstroNet-K2, Matt is looking at this.  Just so you are aware, the maintainers work on this project in their spare time, this is not our day job, so we'll do the best we can.  Neither of us work on windows systems, so will need to source alternative hardware.  In the spirit of open-source, if you find a solution to this then we would be happy to receive a pull request.  Many thanks.
