### ISSUE TITLE
Colon in property names

### ISSUE THREAD

**Issue by kyrylkov** [jsonata-js/jsonata#525]
JSONata throws an error when trying to access a property with colon.  For example: 

```
jsonata(`**.a:b`).evaluate({
  "a": {
    "b": {
      "c": {
        "a:b": ["4545"]
      }
    }
  }
)
```

results in 

```
{
  code: 'S0201',
  position: 5,
  token: ':',
  stack: 'Error\n' +
    '    at handleError (C:\\Users\\dev\\node_modules\\jsonata\\jsonata.js:5969:30)\n' +
    '    at parser (C:\\Users\\dev\\node_modules\\jsonata\\jsonata.js:6930:13)\n' +
    '    at jsonata (C:\\Users\\dev\\node_modules\\jsonata\\jsonata.js:5464:19)\n' +
    ........................
  message: 'Syntax error: ":"'
}
```

**Comment by andrew-coleman** [comment]
Your expression needs to be
```
**.`a:b`
```

See last bullet point here: https://docs.jsonata.org/simple#examples
