### ISSUE TITLE
error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by waclaw66** [jsonata-js/jsonata#575]
Could you please update necessary dependencies to get rid of following error?

```
(node:298825) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
Starting the development server...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/usr/local/jsonata-exerciser/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/usr/local/jsonata-exerciser/node_modules/webpack/lib/NormalModule.js:386:16)
    at handleParseError (/usr/local/jsonata-exerciser/node_modules/webpack/lib/NormalModule.js:434:10)
    at /usr/local/jsonata-exerciser/node_modules/webpack/lib/NormalModule.js:466:5
    at /usr/local/jsonata-exerciser/node_modules/webpack/lib/NormalModule.js:327:12
    at /usr/local/jsonata-exerciser/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/usr/local/jsonata-exerciser/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/usr/local/jsonata-exerciser/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/usr/local/jsonata-exerciser/scripts/start.js:11
  throw err;
  ^
```

using Fedora 36, node v16.14.0, OpenSSL 3.0.2

**Comment by waclaw66** [comment]
closing in favour of https://github.com/jsonata-js/jsonata-exerciser/issues/19
